services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
  sandbox:
    build:
      dockerfile: sandbox.dockerfile
    command: ["sleep", "infinity"]
  ui:
    build:
      dockerfile: ui.dockerfile
    ports:
      - 8080:80
    restart: unless-stopped
volumes:
  ollama: